/**
 * Creates a fix PR for an approved support ticket.
 *
 * Safety guarantees:
 * - Never commits to `main` (or whatever GITHUB_BASE_BRANCH is set to).
 * - Only touches the exact files listed in `files` — every other file in
 *   the repo is left completely untouched.
 * - Uses the GitHub Contents API per-file, so there is no working-copy
 *   checkout, no full-repo overwrite, and no risk of clobbering unrelated
 *   changes that may have landed on main since this branch was cut.
 * - Returns a PR URL. Nothing is merged automatically — a human reviews
 *   and merges (or closes) it.
 *
 * Requires env var GITHUB_TOKEN — a fine-grained PAT scoped to this repo
 * only, with Contents: Read/Write and Pull requests: Read/Write.
 */

const GITHUB_OWNER = process.env.GITHUB_REPO_OWNER || 'sandhyasneha';
const GITHUB_REPO = process.env.GITHUB_REPO_NAME || 'archai-frontend';
const BASE_BRANCH = process.env.GITHUB_BASE_BRANCH || 'main';
const API_ROOT = 'https://api.github.com';

interface PatchedFile {
  path: string; // repo-relative path, e.g. "app/api/blueprints/download/route.ts"
  patched_content: string; // full new file content (not a diff)
}

interface CreateFixPRParams {
  ticketId: string;
  fixSummary: string;
  diagnosis: string;
  files: PatchedFile[];
}

interface CreateFixPRResult {
  branch: string;
  prUrl: string;
  prNumber: number;
}

async function ghFetch(path: string, init?: RequestInit) {
  const res = await fetch(`${API_ROOT}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API error ${res.status} on ${path}: ${body}`);
  }
  return res.json();
}

export async function createFixPR({
  ticketId,
  fixSummary,
  diagnosis,
  files,
}: CreateFixPRParams): Promise<CreateFixPRResult> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is not set — cannot create fix PR.');
  }
  if (!files.length) {
    throw new Error('No files to patch — refusing to open an empty PR.');
  }

  const branch = `fix/ticket-${ticketId.slice(0, 8)}`;

  // 1. Get the latest commit SHA on the base branch (read-only)
  const baseRef = await ghFetch(
    `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/ref/heads/${BASE_BRANCH}`
  );
  const baseSha = baseRef.object.sha;

  // 2. Create the new branch pointing at that SHA. If it already exists
  //    (e.g. retrying an approval), fall through and reuse it.
  try {
    await ghFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });
  } catch (err) {
    if (!String(err).includes('Reference already exists')) throw err;
  }

  // 3. Commit each patched file individually via the Contents API.
  //    This only ever writes the specific file path given — nothing else
  //    in the tree is read, moved, or overwritten.
  for (const file of files) {
    let existingSha: string | undefined;
    try {
      const existing = await ghFetch(
        `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${file.path}?ref=${branch}`
      );
      existingSha = existing.sha;
    } catch {
      // file doesn't exist yet on this branch — that's fine, it's a new file
    }

    await ghFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${file.path}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `fix(ticket-${ticketId.slice(0, 8)}): ${fixSummary}`,
        content: Buffer.from(file.patched_content, 'utf-8').toString('base64'),
        branch,
        ...(existingSha ? { sha: existingSha } : {}),
      }),
    });
  }

  // 4. Open the PR against BASE_BRANCH. Not auto-merged, not auto-deployed.
  const pr = await ghFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: `Fix: ${fixSummary} (ticket ${ticketId.slice(0, 8)})`,
      head: branch,
      base: BASE_BRANCH,
      body:
        `**Support ticket:** ${ticketId}\n\n` +
        `**Diagnosis:**\n${diagnosis}\n\n` +
        `**Fix summary:**\n${fixSummary}\n\n` +
        `_Generated by the Support Triage Agent. This PR was opened after admin approval and has not been merged or deployed — please review and test before merging._`,
    }),
  });

  return { branch, prUrl: pr.html_url, prNumber: pr.number };
}
