import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | ArchAI',
  description: 'Terms of Service for ArchAI, an AI-powered cloud architecture platform operated by Nexplan IT LLC.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="border-b border-gray-100 px-7 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2.5">
          <div className="w-6 h-6 bg-black rounded flex items-center justify-center text-white text-xs font-bold">A</div>
          <span className="text-sm font-bold tracking-widest uppercase">ArchAI</span>
        </Link>
        <Link href="/signin" className="text-xs text-gray-400 hover:text-black transition-colors">← Back to sign in</Link>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-14">
        <h1 className="text-3xl font-medium tracking-tight text-black mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: 7 July 2026</p>

        <div className="flex flex-col gap-8 text-sm leading-relaxed text-gray-700">

          <section>
            <p>
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of ArchAI, a cloud
              architecture automation platform available at arch.nexplan.io (the &quot;Service&quot;), operated by
              Nexplan IT LLC (&quot;Nexplan,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By creating an account or
              using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">1. The Service</h2>
            <p>
              ArchAI uses AI agents to generate cloud architecture blueprints, Infrastructure-as-Code
              (&quot;IaC&quot;), security and compliance findings, cost estimates, disaster recovery plans, and
              migration plans for new (&quot;Greenfield&quot;) and existing (&quot;Brownfield&quot;) cloud infrastructure,
              based on prompts, descriptions, or infrastructure code you provide.
            </p>
          </section>

          <section className="rounded-xl border-2 border-amber-200 bg-amber-50 p-5">
            <h2 className="text-lg font-semibold text-black mb-2">2. Cost Estimates Are Indicative Only — Not Live Pricing</h2>
            <p>
              All cost figures shown by the Service — including monthly cost estimates, multi-cloud cost
              comparisons, cost-before/cost-after migration projections, and identified &quot;cost waste&quot; — are
              <strong> ballpark, indicative estimates only</strong>. They are calculated from static, standard
              on-demand reference pricing at the time the blueprint or migration plan was generated. They are
              <strong> not</strong> retrieved from live cloud provider pricing APIs, and do not account for your
              negotiated enterprise discounts, reserved instance or savings plan commitments, regional pricing
              variations, currently applicable promotions, or recent price changes by AWS, Azure, or Google
              Cloud.
            </p>
            <p className="mt-3">
              These figures are provided for planning and comparison purposes only. Before making any
              purchasing, budgeting, or financial decision, you must independently verify actual current pricing
              using the official pricing calculator or console of the relevant cloud provider.
            </p>
          </section>

          <section className="rounded-xl border-2 border-amber-200 bg-amber-50 p-5">
            <h2 className="text-lg font-semibold text-black mb-2">3. Verify Before You Deploy</h2>
            <p>
              Blueprints, Terraform/IaC output, security findings, audit results, migration plans, and disaster
              recovery configurations generated by the Service (whether via the Greenfield or Brownfield
              workflow) are produced by automated AI agents and are provided <strong>&quot;as is,&quot; without
              warranty of correctness, security, or fitness for any particular purpose</strong>.
            </p>
            <p className="mt-3">
              Before deploying any generated code, applying any migration plan, or otherwise acting on Service
              output in any staging, production, or live environment, you are solely responsible for
              independently reviewing, testing, and validating that output with qualified engineering or
              architecture personnel. Nexplan IT LLC is not liable for any downtime, data loss, security
              incident, cost overrun, compliance failure, or other damages arising from deploying or acting on
              AI-generated output without such independent review.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">4. Accounts &amp; Eligibility</h2>
            <p>
              The Service is intended for business and organisational use. You must register with a valid
              organisation email address; personal email domains (e.g. Gmail, Yahoo) are not permitted. You are
              responsible for maintaining the confidentiality of your account credentials and for all activity
              under your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 flex flex-col gap-1">
              <li>Use the Service to generate infrastructure for unlawful, fraudulent, or malicious purposes;</li>
              <li>Attempt to circumvent usage limits, plan gating, or security controls of the Service;</li>
              <li>Submit input containing another party&apos;s confidential or proprietary infrastructure without authorisation;</li>
              <li>Reverse engineer, decompile, or attempt to extract the underlying models or agent prompts of the Service;</li>
              <li>Resell or sublicense access to the Service without a written agreement with Nexplan IT LLC.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">6. Subscription Plans &amp; Billing</h2>
            <p>
              The Service is offered under Scout (free), Pro, Team, and Enterprise plans, each with different
              usage limits and features as described on our pricing page. Paid plans are billed on a recurring
              basis until cancelled. Fees are non-refundable except as required by law or as otherwise stated at
              time of purchase.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">7. Intellectual Property</h2>
            <p>
              You retain ownership of the prompts, descriptions, and infrastructure code you submit, and of the
              Terraform/IaC output generated for your account. Nexplan IT LLC retains all rights to the
              underlying Service, including the platform, agent orchestration logic, and user interface.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Nexplan IT LLC and its officers, employees, and agents
              shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
              including loss of profits, data, or business, arising out of or related to your use of the
              Service, including without limitation any reliance on cost estimates or generated infrastructure
              output as described in Sections 2 and 3 above.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service if you violate these Terms. You may cancel
              your account at any time from your account settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">10. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes take
              effect constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Montana, United States, without regard to
              conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-black mb-2">12. Contact</h2>
            <p>
              Nexplan IT LLC<br />
              1001 S Main Street, STE 600<br />
              Kalispell, MT 59901<br />
              <a href="mailto:info@nexplanit.com" className="text-black underline">info@nexplanit.com</a>
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
